imu_type: 7
imu_frame: imu_link
i2c_bus: 1
i2c_slave_address: 104
fusion_type: 2

mpu9250: 
  compass_sample_rate: 40
  gyro_accel_sample_rate: 80
  accel_low_pass_filter: 3
  accel_full_scale_range: 16
  gyro_low_pass_filter: 3
  gyro_full_scale_range: 16

calib: 
  compass_min: [-37.671654, -49.161552, -63.558655]
  compass_max: [50.009651, 37.532814, 14.418786]
  accel_min: [-1.003242, -0.99192, -1.039375]
  accel_max: [1.019123, 1.020273, 0.986038]
