nb_of_topics: 4
rate: 10
topic_1:
  name: imu
  topic_name: /imu/data
  min_freq: 40
  use_average: false
  monitoring_rate: 10

topic_2:
  name: depth_camera
  topic_name: /d435/depth/color/points
  min_freq: 3
  use_average: false
  monitoring_rate: 10

topic_3:
  name: gps
  topic_name: /fix
  min_freq: 0.5
  use_average: false
  monitoring_rate: 10

topic_4:
  name: base_odom
  topic_name: /base_odom
  min_freq: 5
  use_average: true
  monitoring_rate: 5