
zeus:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  right_rocker_bogie_controller:
    type: effort_controllers/JointPositionController
    joint: rocker_right_joint
    pid: {p: 2000.0, i: 10.0, d: 10.0}

  right_front_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: right_front_wheel_joint
      pid: {p: 15.0, i: 0.0, d: 0.0}

  right_rear_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid: {p: 15.0, i: 0.0, d: 0.0}

  left_front_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_front_wheel_joint
    pid: {p: 15.0, i: 0.0, d: 0.0}

  left_rear_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_rear_wheel_joint
    pid: {p: 15.0, i: 0.0, d: 0.0} 

  gazebo_ros_control:   
    pid_gains:
      right_front_wheel_joint:
        p: 10.0
        i: 0.0 
        d: 0.0

      right_rear_wheel_joint:
        p: 10.0
        i: 0.0 
        d: 0.0

      left_front_wheel_joint:
        p: 10.0
        i: 0.0 
        d: 0.0

      left_rear_wheel_joint:
        p: 10.0
        i: 0.0 
        d: 0.0 